export const codenames = {
    A: "Alpha Co",
    B: "Bravo Co",
    C: "Charlie Co",
    D: "Delta Co",
    E: "Echo Co",
    F: "Foxtrot Co",
    G: "Golf Co",
    H: "Hotel Co",
    I: "India Co",
    J: "Juliet Co",
    K: "Kilo Co",
    L: "Lima Co",
    M: "Mike Co",
    N: "November Co",
    O: "Oscar Co",
    P: "Papa Co",
    Q: "Quebec Co",
    R: "Romeo Co",
    S: "Sierra Co",
    T: "Tango Co",
    U: "Uniform Co",
    V: "Victor Co",
    W: "Whiskey Co",
    X: "X-Ray Co",
    Y: "Yankee Co",
    Z: "Zulu Co"
};